name: Build
on:
    push:
        branches:
            - main
jobs:
    lint:
        strategy:
            matrix:
                node-version: [20, 21, 22, 23]
                os: ['ubuntu-latest', 'ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04']
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install deps
              run: npm ci
            - name: Lint
              run: npm run lint
    build:
        needs: [lint]
        runs-on: main-server
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                file: Dockerfile
                push: false
                tags: nuqta/nuqta-landing:latest