name: Check
on:
    push:
        branches:
            - main
            - dev
jobs:
    lint:
        strategy:
            matrix:
                node-version: [20, 21, 22, 23]
                os-version: ['ubuntu-latest', 'ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04', 'Windows11AbuPC']
        runs-on: ${{ matrix.os-version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install deps
              run: npm ci
            - name: Lint
              run: npm run lint